name: STRiDE
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=25.0=py39h06a4308_0
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - ace-tools==0.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - colour==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - dos2unix==1
      - fonttools==4.56.0
      - idna==3.10
      - importlib-resources==6.5.2
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - matplotlib==3.9.4
      - mlxtend==0.23.4
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==2.0.2
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.1
      - pysam==0.23.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - shap==0.48.0
      - shapiq==1.2.1
      - six==1.17.0
      - skrebate==0.62
      - slicer==0.0.8
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - typing-extensions==4.14.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - zipp==3.21.0
